### ISSUE TITLE
user not found problem

### ISSUE THREAD

**Issue by shreyzeous21** [nyintosh/drive-ce#1]
Unhandled Runtime Error
ConvexError: [CONVEX Q(users:findUserByAuthId)] [Request ID: 7726fe505eca9c6a] Server Error
Uncaught ConvexError: User not found
    at handler (../../convex/users.ts:140:2)

  Called by client

Source
src/providers/AppContextProvider.tsx (35:2) @ api

  33 | 	const { user } = useUser();
  34 | 	const userInfo = useQuery(
> 35 | 		api.users.findUserByAuthId,
     | 	^
  36 | 		user?.id ? { id: user.id } : 'skip',
  37 | 	);
  38 |

**Comment by nyintosh** [comment]
Hey @shreyzeous21, to resolve this issue, you'll need to set up webhooks in Clerk. Additionally, don't forget to configure the corresponding environment variables. Let me know if you need any further assistance with this!
